const $ = (q, root=document) => root.querySelector(q);
const main = $('#main');
let documents = [], conversations = [], current = null, busy = false, view = 'assistant', lang = 'en';
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pdfURL = d => '/documents/' + encodeURIComponent(d.source_file) + (d.page_number ? '#page=' + d.page_number : '');
const translations = {
 en: {newChat:'New conversation',workspace:'WORKSPACE',assistant:'AI Assistant',library:'Standards library',services:'BIS services',recent:'THIS SESSION',welcome:'A little guidance.<br>A higher standard.',intro:'Find the right standards, understand the details,<br>and take your next step with confidence.',start:'A good place to start'},
 hi: {newChat:'नई बातचीत',workspace:'कार्यक्षेत्र',assistant:'AI सहायक',library:'मानक पुस्तकालय',services:'BIS सेवाएँ',recent:'इस सत्र में',welcome:'थोड़ा मार्गदर्शन।<br>एक बेहतर मानक।',intro:'सही मानक खोजें और आवश्यकताओं को समझें।<br>अपनी भाषा में BIS के बारे में पूछें।',start:'यहाँ से शुरू करें'},
 ta: {newChat:'புதிய உரையாடல்',workspace:'பணியிடம்',assistant:'AI உதவியாளர்',library:'தரநிலைகள்',services:'BIS சேவைகள்',recent:'இந்த அமர்வு',welcome:'சிறிய வழிகாட்டுதல்.<br>உயர்ந்த தரநிலை.',intro:'சரியான தரநிலைகளைக் கண்டறியுங்கள்.<br>உங்கள் மொழியில் BIS பற்றி கேளுங்கள்.',start:'இங்கே தொடங்குங்கள்'}
};
function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=(translations[lang] || translations.en)[el.dataset.i18n]);$('#page-label').textContent=(translations[lang] || translations.en)[view];}
function bindPrompts(){main.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>ask(b.dataset.prompt));main.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>navigate('services'));}
function bindForm(){const form=$('#ask-form'); if(!form)return;form.onsubmit=e=>{e.preventDefault();ask($('#question').value)};$('#question').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();form.requestSubmit()}};$('.send',form).disabled=busy;bindVoice(form);}
function navigate(next){view=next;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===next);b.setAttribute('aria-current',b.dataset.view===next?'page':'false')});$('#sidebar').classList.remove('open');if(next==='assistant')renderAssistant();if(next==='library')renderLibrary();if(next==='services')renderServices();translate();}
function renderAssistant(){if(!current){main.replaceChildren($('#home-template').content.cloneNode(true));bindPrompts();bindForm();translate();return;}const composer=$('#home-template').content.querySelector('form').outerHTML;main.innerHTML=`<section class="conversation"><div id="messages" aria-live="polite"></div>${composer}<p class="source-note">Source-backed guidance · Check publication status and current applicability.</p></section>`;const messages=$('#messages');current.messages.forEach(m=>{const el=document.createElement('article');el.className='message '+m.role;if(m.role==='user'){el.textContent=m.text}else{el.innerHTML='<div class="message-title">✦ &nbsp; Manak <span class="tag">BIS assistant</span></div><div class="answer-text"></div>';$('.answer-text',el).innerHTML=markdown(m.text);renderRichAnswer(el,m);if(m.sources?.length){el.insertAdjacentHTML('beforeend','<p class="answer-note">Retrieved excerpts may be from drafts. Confirm applicability and publication status in the original document.</p>');m.sources.forEach((d,i)=>el.insertAdjacentHTML('beforeend',`<a class="citation" href="${pdfURL(d)}" target="_blank" rel="noopener">[${i+1}] ${escapeHTML(d.document_no)} · Page ${escapeHTML(d.page_number)} ↗<small>${escapeHTML(d.title)}</small></a>`));}}messages.append(el)});if(busy)messages.insertAdjacentHTML('beforeend','<div class="status" role="status">Searching the connected documents…</div>');bindForm();}
async function ask(query){if(busy)return;query=typeof query==='string'?query.trim():'';if(query.length<2||query.length>1500){$('#question')?.setCustomValidity('Enter a question between 2 and 1,500 characters.');$('#question')?.reportValidity();if($('#question'))$('#question').oninput=()=>$('#question').setCustomValidity('');return;}if(!current){current={title:query,messages:[]};conversations.unshift(current);}const target=current;target.messages.push({role:'user',text:query});busy=true;navigate('assistant');renderHistory();try{const response=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,language:lang}),signal:AbortSignal.timeout(45000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Search failed.');target.messages.push({role:'assistant',text:data.answer,sources:data.retrieved_passages||[],citations:data.citations||[],actions:data.action_cards||[],mode:data.mode,language:data.language,warnings:data.warnings||[]});return {answer:data.answer,sources:(data.retrieved_passages||[]).map(d=>({document:d.document_no,page:d.page_number}))};}catch(error){target.messages.push({role:'assistant',text:'Unable to complete the search. '+(error.name==='TimeoutError'?'The search timed out. Please try again.':error.message)});}finally{busy=false;if(view==='assistant')renderAssistant();}}
function renderHistory(){const history=$('#history');history.replaceChildren();conversations.slice(0,8).forEach(c=>{const b=document.createElement('button');b.className='history-item';b.textContent='◷  '+c.title;b.title=c.title;b.onclick=()=>{current=c;navigate('assistant')};history.append(b)});}
function renderLibrary(){main.innerHTML=`<section class="view"><div class="eyebrow" style="text-align:left">YOUR CONNECTED KNOWLEDGE</div><h1>Standards library</h1><p class="intro">Explore your medical equipment and hospital planning collection.</p><div class="filters"><input id="library-search" type="search" aria-label="Search documents" placeholder="Search by product, title, or document number…"><select id="committee" aria-label="Filter by committee"><option value="">All committees</option>${[...new Set(documents.map(d=>d.committee))].sort().map(c=>`<option>${escapeHTML(c)}</option>`).join('')}</select></div><p class="status" id="result-count"></p><div id="document-list" class="document-list"></div></section>`;$('#library-search').oninput=filterDocuments;$('#committee').onchange=filterDocuments;filterDocuments();}
function filterDocuments(){const q=$('#library-search').value.toLowerCase();const committee=$('#committee').value;const results=documents.filter(d=>(d.title+' '+d.document_no).toLowerCase().includes(q)&&(!committee||d.committee===committee));$('#result-count').textContent=`${results.length} of ${documents.length} documents`;$('#document-list').innerHTML=results.length?results.map(d=>`<article class="document-card"><span class="meta">${escapeHTML(d.document_no)}</span>${d.document_no.includes('WC')?'<span class="tag">Draft · WC</span>':''}<h3>${escapeHTML(d.title)}</h3><div class="meta">${escapeHTML(d.committee)} · ${d.num_pages} pages</div><a href="${pdfURL(d)}" target="_blank" rel="noopener">Open source PDF ↗</a></article>`).join(''):'<p class="status">No matching documents. Try another product or committee.</p>';}
function renderServices(){const services=[['Product certification','Find official information about product certification and application procedures.','https://www.bis.gov.in/'],['Hallmarking','Explore official hallmarking resources and consumer information.','https://www.bis.gov.in/'],['Testing laboratories','Look up testing facilities through the BIS laboratory portal.','https://lims.bis.gov.in/'],['Consumer support','Access consumer resources and contact information on the BIS website.','https://www.bis.gov.in/']];main.innerHTML=`<section class="view"><div class="eyebrow" style="text-align:left">OFFICIAL RESOURCES</div><h1>BIS services</h1><p class="intro">Continue your journey with official BIS resources.</p><div class="scope-notice" style="margin:0 0 25px"><span>ⓘ</span><p>Ask for certification, hallmarking, laboratory and complaint guidance. Use official portals to verify live records and submit applications.</p></div><div class="service-grid">${services.map(([title,description,url])=>`<article class="document-card"><span class="card-icon teal">◇</span><h3>${title}</h3><p>${description}</p><a href="${url}" target="_blank" rel="noopener">Visit official portal ↗</a></article>`).join('')}</div></section>`;}
$('#new-chat').onclick=()=>{current=null;navigate('assistant')};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#language').onchange=e=>{lang=e.target.value;translate()};
navigate('assistant');fetch('/api/documents').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{documents=data.documents;$('#doc-count').textContent=`${data.metadata.total_documents} documents · ${data.metadata.total_chunks} passages`;if(view==='library')renderLibrary()}).catch(()=>{$('#doc-count').textContent='Collection unavailable. Restart the local server.'});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_bis_documents',title:'Search BIS documents',description:'Search the connected Domain 54 documents and show the answer and sources in the conversation.',inputSchema:{type:'object',properties:{query:{type:'string',minLength:2,maxLength:1500}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||typeof input.query!=='string'||input.query.trim().length<2||input.query.length>1500)throw Error('A question between 2 and 1,500 characters is required.');if(busy)throw Error('A search is already running.');return await ask(input.query);}})).catch(()=>{});}catch{}}

function safeURL(value){
 try{const url=new URL(value,location.origin);if(url.origin===location.origin&&url.pathname.startsWith('/documents/'))return url.href;
 if(url.protocol==='https:'&&(['bis.gov.in','crsbis.in','manakonline.in','pib.gov.in','cpcb.nic.in'].some(host=>url.hostname===host||url.hostname.endsWith('.'+host))))return url.href;}catch{}
 return null;
}
function markdown(text){
 // Escaping precedes formatting; raw HTML and arbitrary model URLs never execute.
 const inline=line=>escapeHTML(line).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');
 return String(text).split(/\n\n+/).map(part=>{
 const lines=part.split('\n');
 if(lines.every(line=>/^\d+\. /.test(line)))return '<ol>'+lines.map(line=>'<li>'+inline(line.replace(/^\d+\. /,''))+'</li>').join('')+'</ol>';
 if(lines.every(line=>/^[-*] /.test(line)))return '<ul>'+lines.map(line=>'<li>'+inline(line.slice(2))+'</li>').join('')+'</ul>';
 return '<p>'+lines.map(line=>/^#{1,3} /.test(line)?'<strong>'+inline(line.replace(/^#{1,3} /,''))+'</strong>':inline(line)).join('<br>')+'</p>';
 }).join('');
}
function renderRichAnswer(el,m){
 const tools=document.createElement('div');tools.className='answer-tools';
 const copy=document.createElement('button');copy.textContent='Copy';copy.onclick=async()=>{try{await navigator.clipboard.writeText(m.text);copy.textContent='Copied';}catch{copy.textContent='Copy unavailable';}};tools.append(copy);
 if('speechSynthesis' in window){const speak=document.createElement('button');speak.textContent='Read aloud';speak.onclick=()=>{if(speechSynthesis.speaking){speechSynthesis.cancel();speak.textContent='Read aloud';return;}const utterance=new SpeechSynthesisUtterance(m.text);utterance.lang=(m.language||lang)+'-IN';utterance.onend=()=>speak.textContent='Read aloud';utterance.onerror=()=>speak.textContent='Voice unavailable';speechSynthesis.speak(utterance);speak.textContent='Stop reading';};tools.append(speak);}
 const mode=document.createElement('span');mode.textContent=m.mode==='openai'?'AI · cited evidence':'Local · source-backed';tools.append(mode);el.append(tools);
 if(m.warnings?.length){const note=document.createElement('p');note.className='answer-note';note.textContent='Using local guidance. Full requested-language translation may be unavailable.';el.append(note);}
 (m.citations||[]).forEach(c=>{const url=safeURL(c.url);if(!url)return;const a=document.createElement('a');a.className='citation-chip';a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='['+c.id+'] '+c.title+(c.page?' · p. '+c.page:'');a.title=(c.status||c.kind)+' · Reviewed '+c.reviewed_on;el.append(a);});
 if(m.actions?.length){const cards=document.createElement('div');cards.className='answer-actions';m.actions.forEach(card=>{const url=safeURL(card.url);if(!url)return;const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=card.title+' ↗';cards.append(a);});el.append(cards);}
}
function bindVoice(form){
 const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
 if(!Recognition)return;
 const button=document.createElement('button');button.type='button';button.className='voice-button';button.textContent='Dictate';button.title='Browser speech recognition may send audio to its speech service';button.disabled=busy;
 button.onclick=()=>{const recognition=new Recognition();recognition.lang=lang+'-IN';recognition.interimResults=false;recognition.onstart=()=>{button.textContent='Listening…';button.disabled=true;};recognition.onresult=event=>{$('#question').value=event.results[0][0].transcript;};recognition.onerror=()=>button.textContent='Microphone unavailable';recognition.onend=()=>{button.disabled=false;if(button.textContent==='Listening…')button.textContent='Dictate';};try{recognition.start();}catch{button.textContent='Microphone unavailable';}};
 $('.composer-bottom',form).prepend(button);
}
